apiVersion: apps/v1
kind: Deployment
metadata:
  name: pizzastore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pizzastore
  template:
    metadata:
      labels:
        app: pizzastore
    spec:
      containers:
      - name: pizzastore
        image: jackyxu2018/pizzastore
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: "http"
        env:
        # Define the environment variable
        - name: Geodecluster-locators
          valueFrom:
            configMapKeyRef:
              # The ConfigMap containing the value you want to assign to gemfire-cluster-info
              # {cluster_name}-configmap such as gemfire-cluster1-geode-configmap
              name: gemfire-cluster1-geode-configmap
              # Specify the key associated with the value
              key: locators
        - name: Geodeclient-log-level
          value: "config"
        - name: Geodeclient-log-file
          value: "/var/log/geodeclient.log"

---
apiVersion: v1
kind: Service
metadata:
  name: pizzastoreservice
spec:
  selector:
    app: pizzastore
  ports:
  - name: http
    protocol: TCP
    port: 8080
    nodePort: 32321
  type: NodePort
