apiVersion: apps/v1
kind: Deployment
metadata:
  name: pizzastore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pizzastore
  template:
    metadata:
      labels:
        app: pizzastore
    spec:
      containers:
      - name: pizzastore
        image: jackyxu2018/pizzastore
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: "http"
---
apiVersion: v1
kind: Service
metadata:
  name: pizzastoreservice
spec:
  selector:
    app: pizzastore
  ports:
  - name: http
    protocol: TCP
    port: 8080
    nodePort: 32321
  type: NodePort
