{{- if .Values.rest.ingress.enabled -}}
{{- $fullName := include "geode.fullname" . -}}
{{- $ingressPath := .Values.rest.ingress.path -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}-rest
  labels:
    app: {{ template "geode.name" . }}-server
    chart: {{ template "geode.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.rest.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.rest.ingress.tls }}
  tls:
  {{- range .Values.rest.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.rest.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $fullName }}-rest
              servicePort: 9090
  {{- end }}
{{- end }}